#!/usr/bin/env bash
# Idempotently ensures a fixed test student account exists in the LOCAL
# Supabase Auth instance only, for unattended Playwright / synthetic
# persona runs (see docs/iterative-development-playwright-process.md and
# synthetic/README.md).
#
# Safety rail: this script only ever talks to the local Supabase stack.
# It does not accept a URL argument or read one from the environment —
# there is no way to point it at a hosted project.
set -euo pipefail

SUPABASE_URL="http://127.0.0.1:54321"
EMAIL="${PLAYWRIGHT_ADMIN_EMAIL:-aiden@local.test}"
PASSWORD="${PLAYWRIGHT_ADMIN_PASSWORD:-aiden-local-test-password}"
ENV_FILE=".env.playwright"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

STATUS_JSON="$(npx supabase status -o json 2>/dev/null || true)"
if [ -z "$STATUS_JSON" ]; then
  echo "Local Supabase stack is not running. Run 'npx supabase start' first." >&2
  exit 1
fi

SERVICE_KEY="$(echo "$STATUS_JSON" | jq -r '.SERVICE_ROLE_KEY // .SECRET_KEY // empty')"
if [ -z "$SERVICE_KEY" ]; then
  echo "Could not read a service/secret key from 'supabase status -o json'." >&2
  exit 1
fi

EXISTING_ID="$(curl -sS "${SUPABASE_URL}/auth/v1/admin/users?email=$(printf '%s' "$EMAIL" | jq -sRr @uri)" \
  -H "apikey: ${SERVICE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_KEY}" \
  | jq -r '.users[0].id // empty')"

if [ -n "$EXISTING_ID" ]; then
  echo "Playwright test account already exists (${EMAIL})."
else
  echo "Creating Playwright test account (${EMAIL})..."
  CREATE_RESPONSE="$(curl -sS -X POST "${SUPABASE_URL}/auth/v1/admin/users" \
    -H "apikey: ${SERVICE_KEY}" \
    -H "Authorization: Bearer ${SERVICE_KEY}" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg email "$EMAIL" --arg password "$PASSWORD" \
      '{email: $email, password: $password, email_confirm: true}')")"

  ERROR_MSG="$(echo "$CREATE_RESPONSE" | jq -r '.msg // .error_description // empty')"
  if [ -n "$ERROR_MSG" ]; then
    echo "Failed to create test account: ${ERROR_MSG}" >&2
    exit 1
  fi
  echo "Created."
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-playwright-test-account.sh — local dev only.
PLAYWRIGHT_ADMIN_EMAIL=${EMAIL}
PLAYWRIGHT_ADMIN_PASSWORD=${PASSWORD}
EOF

echo "Wrote credentials to ${ENV_FILE} (gitignored)."
